spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://smartsearch.c7suc62aqtqi.ca-central-1.rds.amazonaws.com:3306/smartsearch?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8